name: Node.js CI

on:
  push:
    branches: [ main ]
    
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm --prefix /var/www/html/ install --force
    - run:  npm  run --prefix /var/www/html/ build
    - run:  mv /var/www/htmlt/appleredesign/dist/* /var/www/html/